default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: sleep_tracker_development
  username: <%= ENV.fetch('DB_USER', 'user') %>
  password: <%= ENV.fetch('DB_PASSWORD', '123456') %>
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  port: <%= ENV.fetch('DB_PORT', 5432) %>

test:
  <<: *default
  database: sleep_tracker_test
  username: <%= ENV.fetch('DB_USER', 'user') %>
  password: <%= ENV.fetch('DB_PASSWORD', '123456') %>
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  port: <%= ENV.fetch('DB_PORT', 5432) %>

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
